import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/providers/SessionProvider";
import { ConvexClientProvider } from "@/providers/convex-client-provider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body className={`${poppins.className}`}>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </body>
      </SessionWrapper>
    </html>
  );
}
